name:                free-package
version:             0.1.0.0
github:              "gbogard/free-monads-from-scratch"
license:             MIT
author:              "Guillaume Bogard"
maintainer:          "hey@guillaumebogard.dev"

dependencies:
- base >= 4.7 && < 5
- free

library:
  source-dirs: src

executables: {}
tests: {}