name:                data-types-a-la-carte
version:             0.1.0.0
github:              "gbogard/free-monads-from-scratch"
license:             MIT
author:              "Guillaume Bogard"
maintainer:          "hey@guillaumebogard.dev"

dependencies:
- base >= 4.7 && < 5
- hspec

library:
  source-dirs: src

executables: {}

tests:
  a-la-carte-tests:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - data-types-a-la-carte